const ADD_HABIT = 'ADD_HABIT';
const UPDATE_HABIT = 'UPDATE_HABIT';
const REMOVE_HABIT = 'REMOVE_HABIT';
const ADD_USER = 'ADD_USER';
const UPDATE_USER = 'UPDATE_USER';

export default { ADD_HABIT, UPDATE_HABIT, REMOVE_HABIT, ADD_USER, UPDATE_USER };
